# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.20.1,1.21)
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=47.4.10
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[47,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,)
# The mapping channel to use for mappings.
mapping_channel=official
# The mapping version to query from the mapping channel.
mapping_version=1.20.1

## Mod Properties

mod_id=vault_ui
mod_name=Create: Vault UI
mod_license=LGPL-3.0-only
mod_version=1.0.0-beta9
mod_group_id=net.yigitguven.vault_ui
mod_authors=Yigit Guven
mod_description=An addon for the Create mod that provides a custom user interface for Vaults.
mod_homepage=https://github.com/yigit-guven/Vault-UI
mod_credits=Special thanks to the Create Team.

# Dependencies
# Create 0.5.1.j (Forge 1.20.1)
create_version=5838779
# Vibrant Vaults 0.2.0 (Forge 1.20.1, compatible with Create 0.5.1.f)
vibrant_vaults_version=6463839
# JEI 15.2.0.27
jei_version=7920915
